# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('relationship', '0002_remove_relationship_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='userImage',
            new_name='userFan',
        ),
        migrations.AddField(
            model_name='relationship',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
